-- MySQL Script generated by MySQL Workbench
-- Sat Jan  6 07:34:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LittleLemonDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LittleLemonDB` ;

-- -----------------------------------------------------
-- Schema LittleLemonDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LittleLemonDB` DEFAULT CHARACTER SET utf8 ;
USE `LittleLemonDB` ;

-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LittleLemonDB`.`Customers` ;

CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Customers` (
  `customerID` INT NOT NULL,
  `customerFirstName` VARCHAR(63) NULL,
  `customerLastName` VARCHAR(63) NULL,
  `customerPhone` VARCHAR(45) NULL,
  `customerEmail` VARCHAR(127) NULL,
  PRIMARY KEY (`customerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Bookings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LittleLemonDB`.`Bookings` ;

CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Bookings` (
  `bookingID` INT NOT NULL,
  `tableNumber` INT NOT NULL,
  `bookingDate` DATE NOT NULL,
  `bookingTime` TIME NULL DEFAULT NULL,
  `customerID` INT NOT NULL,
  PRIMARY KEY (`bookingID`),
  INDEX `customerBooked_idx` (`customerID` ASC) VISIBLE,
  CONSTRAINT `customerBooked`
    FOREIGN KEY (`customerID`)
    REFERENCES `LittleLemonDB`.`Customers` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LittleLemonDB`.`Staff` ;

CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Staff` (
  `staffID` INT NOT NULL,
  `staffFirstName` VARCHAR(127) NULL,
  `staffLastName` VARCHAR(127) NULL,
  `staffRole` VARCHAR(127) NULL,
  `staffSalary` DECIMAL(8,2) NULL,
  `directReport` INT NULL,
  PRIMARY KEY (`staffID`),
  INDEX `reportsToKey_idx` (`directReport` ASC) VISIBLE,
  CONSTRAINT `reportsToKey`
    FOREIGN KEY (`directReport`)
    REFERENCES `LittleLemonDB`.`Staff` (`staffID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`OrderStatuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LittleLemonDB`.`OrderStatuses` ;

CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`OrderStatuses` (
  `orderStatusID` INT NOT NULL,
  `orderDeliveryDate` DATE NULL,
  `orderStatus` VARCHAR(255) NULL,
  `staffID` INT NULL,
  PRIMARY KEY (`orderStatusID`),
  INDEX `staffResponsible_idx` (`staffID` ASC) VISIBLE,
  CONSTRAINT `staffResponsible`
    FOREIGN KEY (`staffID`)
    REFERENCES `LittleLemonDB`.`Staff` (`staffID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`MenuItems`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LittleLemonDB`.`MenuItems` ;

CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`MenuItems` (
  `menuItemID` INT NOT NULL,
  `courseName` VARCHAR(127) NULL,
  `starterName` VARCHAR(127) NULL,
  `dessertName` VARCHAR(127) NULL,
  PRIMARY KEY (`menuItemID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LittleLemonDB`.`Menu` ;

CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Menu` (
  `menuID` INT NOT NULL,
  `menuItem` INT NULL,
  `menuName` VARCHAR(127) NULL,
  `cuisine` VARCHAR(127) NULL,
  PRIMARY KEY (`menuID`),
  INDEX `menuItem_idx` (`menuItem` ASC) VISIBLE,
  CONSTRAINT `menuItem`
    FOREIGN KEY (`menuItem`)
    REFERENCES `LittleLemonDB`.`MenuItems` (`menuItemID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LittleLemonDB`.`Orders` ;

CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`Orders` (
  `orderID` INT NOT NULL,
  `menuItem` INT NOT NULL,
  `quantity` INT NOT NULL,
  `totalCost` DECIMAL(6,2) NOT NULL,
  `orderStatus` INT NOT NULL,
  `customerID` INT NULL,
  PRIMARY KEY (`orderID`),
  INDEX `orderStatus_idx` (`orderStatus` ASC) VISIBLE,
  INDEX `menuItem_idx` (`menuItem` ASC) VISIBLE,
  INDEX `personOrdered_idx` (`customerID` ASC) VISIBLE,
  CONSTRAINT `orderStatus`
    FOREIGN KEY (`orderStatus`)
    REFERENCES `LittleLemonDB`.`OrderStatuses` (`orderStatusID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `menu`
    FOREIGN KEY (`menuItem`)
    REFERENCES `LittleLemonDB`.`Menu` (`menuID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `personOrdered`
    FOREIGN KEY (`customerID`)
    REFERENCES `LittleLemonDB`.`Customers` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`BookingsOrders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LittleLemonDB`.`BookingsOrders` ;

CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`BookingsOrders` (
  `rowID` INT NOT NULL,
  `bookingID` INT NULL,
  `orderID` INT NULL,
  PRIMARY KEY (`rowID`),
  INDEX `bookingKey_idx` (`bookingID` ASC) VISIBLE,
  INDEX `orderID_idx` (`orderID` ASC) VISIBLE,
  CONSTRAINT `bookingKey`
    FOREIGN KEY (`bookingID`)
    REFERENCES `LittleLemonDB`.`Bookings` (`bookingID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orderID`
    FOREIGN KEY (`orderID`)
    REFERENCES `LittleLemonDB`.`Orders` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
